name: Auto-Merge Dependabot Updates

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - package.json
      - package-lock.json

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    name: Enable Auto-Merge for Dependabot
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-22.04

    steps:
      - name: Approve Dependabot PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
